/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PlayerRowItem {
        /**
          * @default ''
         */
        "imageUrl": string;
        /**
          * @default false
         */
        "isAdmin": boolean;
        /**
          * @default false
         */
        "isLoggedIn": boolean;
        /**
          * @default ''
         */
        "league": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default ''
         */
        "position": string;
        /**
          * @default ''
         */
        "team": string;
        /**
          * @default 'players'
         */
        "type": string;
    }
}
export interface PlayerRowItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPlayerRowItemElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPlayerRowItemElementEventMap {
        "editClick": void;
        "deleteClick": void;
        "importClick": void;
    }
    interface HTMLPlayerRowItemElement extends Components.PlayerRowItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPlayerRowItemElementEventMap>(type: K, listener: (this: HTMLPlayerRowItemElement, ev: PlayerRowItemCustomEvent<HTMLPlayerRowItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPlayerRowItemElementEventMap>(type: K, listener: (this: HTMLPlayerRowItemElement, ev: PlayerRowItemCustomEvent<HTMLPlayerRowItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPlayerRowItemElement: {
        prototype: HTMLPlayerRowItemElement;
        new (): HTMLPlayerRowItemElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "player-row-item": HTMLPlayerRowItemElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PlayerRowItem {
        /**
          * @default ''
         */
        "imageUrl"?: string;
        /**
          * @default false
         */
        "isAdmin"?: boolean;
        /**
          * @default false
         */
        "isLoggedIn"?: boolean;
        /**
          * @default ''
         */
        "league"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        "onDeleteClick"?: (event: PlayerRowItemCustomEvent<void>) => void;
        "onEditClick"?: (event: PlayerRowItemCustomEvent<void>) => void;
        "onImportClick"?: (event: PlayerRowItemCustomEvent<void>) => void;
        /**
          * @default ''
         */
        "position"?: string;
        /**
          * @default ''
         */
        "team"?: string;
        /**
          * @default 'players'
         */
        "type"?: string;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface PlayerRowItemAttributes {
        "name": string;
        "team": string;
        "league": string;
        "position": string;
        "imageUrl": string;
        "type": string;
        "isAdmin": boolean;
        "isLoggedIn": boolean;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "player-row-item": Omit<PlayerRowItem, keyof PlayerRowItemAttributes> & { [K in keyof PlayerRowItem & keyof PlayerRowItemAttributes]?: PlayerRowItem[K] } & { [K in keyof PlayerRowItem & keyof PlayerRowItemAttributes as `attr:${K}`]?: PlayerRowItemAttributes[K] } & { [K in keyof PlayerRowItem & keyof PlayerRowItemAttributes as `prop:${K}`]?: PlayerRowItem[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "player-row-item": LocalJSX.IntrinsicElements["player-row-item"] & JSXBase.HTMLAttributes<HTMLPlayerRowItemElement>;
        }
    }
}
